name: cycleGAN
channels:
  - defaults
dependencies:
  - python=3.6
  - pip
  - pip:
    - torch==1.9.0
    - torchvision==0.10.0
    - numpy==1.19.5
    - PyYAML==5.4.1
    - typing==3.7.4.3
    - opencv-python==4.5.3.56
    - natsort==7.1.1
    - Pillow==8.3.1